### ISSUE TITLE
Support 4k content on bowsers with limited MSE buffer

### ISSUE THREAD

**Issue by gesinger** [videojs/http-streaming#192] opened 2018-08-09 17:44 UTC
Tracking PRs (which should eventually get merged into http-streaming):
"handle dynamic buffer sizes (4k support)"
https://github.com/videojs/videojs-contrib-hls/pull/1416
"Graceful handling of QuotaExceededError"
https://github.com/videojs/videojs-contrib-media-sources/pull/178

Related:
https://github.com/videojs/videojs-contrib-hls/issues/1435

**Comment by leonhandreke** [comment] 2019-03-20 18:50
For anybody facing the `Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full` error with high-bitrate videos: I cranked down `videojs.Hls.MAX_GOAL_BUFFER_LENGTH` and `videojs.Hls.GOAL_BUFFER_LENGTH` to 30. I couldn't really make sense of the code in https://github.com/videojs/http-streaming/blob/b820f24f5c3c9dc2deb5449b1d92dd7f7a50ea4d/src/master-playlist-controller.js#L1191 but that fixed it, now the buffer is shorter.

It's an ugly hack but it works ¯\_(ツ)_/¯

**Comment by asadmalik3** [comment] 2019-03-28 12:17
@leonhandreke is there a neat way to change MAX_GOAL_BUFFER_LENGTH from video js?

**Comment by leonhandreke** [comment] 2019-03-28 19:38
@asadmalik3 yes, you can just set `videojs.Hls.MAX_GOAL_BUFFER_LENGTH = 30;` in your code before initializing your player. Hope that helps!

**Comment by johneisenheim** [comment] 2019-09-16 18:42
Hello! Thanks for this fixes...Is there any way to apply the fixes above on MPEG-Dash? On older browser (like Chrome 55) the error is still reproduced with mpd files. Thank you again!

**Comment by jeopard** [comment] 2020-10-06 17:25
Hey! Thank you for all the great work! I just wanted to let you know that the `videojs.Hls.MAX_GOAL_BUFFER_LENGTH = 30;` doesn't work for Firefox, as I still get the append buffer error. I'm using video.js `7.8.4` with http-streaming `1.13.2`. 

I'm guessing this issue is a duplicate of https://github.com/videojs/http-streaming/issues/344 ?

**Comment by gkatsev** [comment] 2020-10-11 07:16
Yup, they're very likely the same issue.

**Comment by gkatsev** [comment] 2021-02-22 16:27
Closing in favor #344.

**Closed by gkatsev** 2021-02-22 16:27 UTC
Labels: bug
