### ISSUE TITLE
Impossible to set playlist after VIDEOJS: WARN: Problem encountered with playlist

### ISSUE THREAD

**Issue by brootle** [videojs/http-streaming#1064] opened 2021-02-09 17:41 UTC
## Description
Changing playlists works fine until it breaks after VideoJS warning.

`VIDEOJS: WARN: Problem encountered with playlist 5-placeholder-uri-5. Excessive main segment downloading detected. Switching to playlist 0-placeholder-uri-0.`
As you can see playlist sets to the 1st one and after that I can't switch to any other available in player.qualityLevels(). I put minimalistic example here https://codepen.io/brootledev/pen/oNYLjJP

## Sources
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

## Steps to reproduce

1. Change quality to max
2. Change quality to min
3. Keep toggling, at some point you will get warning _VIDEOJS: WARN: Problem encountered with playlist_

### Expected
I expect that player will be playing playlist that was set by user

### Error output
`video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 5-placeholder-uri-5. Excessive main segment downloading detected. Switching to playlist 0-placeholder-uri-0.`

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
I am using VideoJS 7.11.4, not sure which videojs-http-streaming version is there

### videojs version
VideoJS 7.11.4, but this will happen at any version starting from 7.10...

### Browsers
what browsers are affected? please include browser and version for each
Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)
Firefox 85.0 (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Windows 10 Pro, Version 2004, OS build 19041.746

### Other Plugins
videojs-contrib-quality-levels

### Other JavaScript
no

**Comment by gkatsev** [comment] 2021-02-11 06:36
some discussion about this in slack starting with https://videojs.slack.com/archives/C0L7W9VL7/p1613022559160400
To summarize, I think this is happening because playback watcher doesn't account for fast quality switches and so it thinks that we are downloading excessively when we're not actually doing so, yet. This means that we exclude the playlist forever, and then it isn't possible to ever re-enable that playlist using contrib-quality-levels.
We already un-exclude playlists when enabled, if it's coming from contrib-quality-levels, we should probably just *always* ignore excludeUntil, even if it's `Infinity`. Right now, `vhs.representations()` won't return these items but `qualityLevels()` seems to still include them.

It's reproducible reliably in the codepen. If it doesn't happen on the first down-up switch, it'll happen on the next one.

**Comment by hgshoggins** [comment] 2021-03-21 19:49
Any idea to overcome this issue? @gkatsev, is it possible to e.g. disable playlist blacklisting until this problem is solved?

**Comment by jamie-usp** [comment] 2021-06-25 20:28
As discussed with @gkatsev via slack. I also came across this issue a repro'd with both a codepen example and local html/js setup. 

Codepen - https://codepen.io/jamiefletchertv/pen/YzZmbmx
Local setup -  macOS - Chrome Version 91.0.4472.114 (Official Build) (x86_64)
```javascript
<html>
<head>
  <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
  <meta charset="utf-8">
  <title>VideoJS DASH Playback Test - Issue #1064 </title>
</head>
<body>
  <h1>VideoJS DASH Playback Test - Issue #1064 </h1>
  <style>
  </style>
  <div id="video-container">
  <video
         id="dash"
         class="video-js"
         controls
         preload="auto"
         width="640"
         height="268"
         autoplay="true"
         muted="muted"
         >
  </video>
</div>
<script src="https://vjs.zencdn.net/7.11.4/video.js"></script>
<!-- Dash.js -->
<script src="http://cdn.dashjs.org/latest/dash.all.debug.js"></script>
<!-- videojs-contrib-dash script -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-dash/4.1.0/videojs-dash.js"></script>-->
<!--<script src="//cdn.dashjs.org/latest/dash.all.debug.js"></script>
<script src="https://unpkg.com/videojs-contrib-dash/dist/videojs-dash.js"></script>-->
<script>
window.onload = function(){
  var dash_player = videojs('dash', { autoplay: true, controls: true, liveui: true });
  dash_player.src({ "type": "application/dash+xml", "src": "https://demo.unified-streaming.com/k8s/vod2live/trunk/unified-learning.isml/.mpd"});
  dash_player.play();
  console.log('Dash Player Current Time', dash_player.currentTime());
  dash_player.on('loadedmetadata', function() {
    var dash_track = dash_player.textTracks()[0];
    dash_track.on('cuechange', (e) => console.log(dash_track.activeCues));
    dash_track.mode = 'disabled';
  });
}
</script>
</body>
</html>
```

**Comment by gkatsev** [comment] 2021-07-02 03:36
Unfortunately, I think that's a separate issue. Your stream includes `$Time$` in the live dash, which we don't support: https://github.com/videojs/http-streaming#dash-assets-with-time-interpolation-and-segmenttimelines-with-no-t.

**Comment by gkatsev** [comment] 2021-07-12 16:20
Once I upgrade to Video.js 7.14.0, or 7.13.3, I can no longer reproduce this issue. Though, In the original code-pen with Video.js 7.11.4 I could reproduce it fairly reliably. I assume it's been fixed by something between then and now.

**Closed** 2022-04-19 17:16 UTC
Labels: outdated

**Comment by mbirth** [comment] 2022-05-02 11:18
Not stale. I've just encountered this after upgrading videojs from 7.8.3 to 7.18.1.

In our case, I have a 12 hour long DVR-stream and want to jump to 10 minutes before end. I've done this via the "playing" event. Now, probably in combination with quality probing, videojs seems to ignore the `player.currentTime(1234)` and thinks it's downloading excessively. Even introducing a delay of 1-3 seconds before seeking doesn't help.

If I omit the seeking, the streams play just fine.

This is with Chrome or Firefox. On Safari I don't see these errors.

**Comment by DanBrownSyncbak** [comment] 2022-05-06 15:57
Having the same issue. Any updates would be appreciated.

**Comment by mbirth** [comment] 2022-05-06 17:47
Version 7.9.7 seems to be the last (stable) one where seeking works. All newer versions don't let me seek - neither via API nor manually by dragging the slider.

**Comment by gesinger** [comment] 2022-05-07 11:22
Hello all! For anyone still experiencing this or a similar issue, the warning shown may be a symptom of various types of problems. For the original post, it seems to be solved. If you are seeing issues similar to this one with your own stream, please open a new issue and provide a sample stream and steps to reproduce, and thank you!

**Comment by arikadiusz** [comment] 2022-05-17 12:22
I see this issue while playing live streams

VIDEOJS: WARN: Problem encountered with playlist 0-level_0.m3u8

**Comment by damanV5** [comment] 2022-10-02 10:21
> Not stale. I've just encountered this after upgrading videojs from 7.8.3 to 7.18.1.
> 
> In our case, I have a 12 hour long DVR-stream and want to jump to 10 minutes before end. I've done this via the "playing" event. Now, probably in combination with quality probing, videojs seems to ignore the `player.currentTime(1234)` and thinks it's downloading excessively. Even introducing a delay of 1-3 seconds before seeking doesn't help.
> 
> If I omit the seeking, the streams play just fine.
> 
> This is with Chrome or Firefox. On Safari I don't see these errors.

@mbirth , I am also facing the same issue . It happens when you seek in the case of very large videos.

After seeking, I got the multiple errors in the console:
**Excessive main segment downloading detected. Switching to playlist 4-index_6.m3u8.**

After some time  : **"Playback cannot continue. No available working or supported playlists"** is displayed on the player.

I have researched,  this only works with videojs version '7.2.3' for now.

Any help would be appreciated as I am using version 7.17.0 .
