### ISSUE TITLE
Cannot read property 'byterange' of undefined 

### ISSUE THREAD

**Issue by PaulCheriyan009** [videojs/http-streaming#511] opened 2019-05-14 04:55 UTC
## Description
The first segment for the file is loaded and the second segment is not loading. After the first segment loaded I get the following error

## Sources
` const options = {`
    `    "preload": "auto",`
`        "width": "100%  ",`
`        techOrder: ['html5'],`
`        html5: {`
`          dash: {`
`            setLimitBitrateByPortal: true,`
`            setMaxAllowedBitrateFor: ['video', 2000]`
`          }`
`        }`
`      };`
`      videojs.options.flash.swf = "http://vjs.zencdn.net/4.2/video-js.swf"`
`      var player = videojs('my-player', options);`
`  player.eme({`
`        emeHeaders: {`
`          'customdata': 'PEtl***************e'`
`        }`
`      });`
`      player.on('ready', function () {`
`        var wvprDashSrc = {`
`          src: 'https********t/manifest.mpd',`
`          type: 'application/dash+xml',``
`          keySystems: {`
`            'com.widevine.alpha': 'https://wv-keyos.licensekeyserver.com/',`
`            'com.microsoft.playready': ``'https://prkeyos.licensekeyserver.com/core/rightsmanager.asmx'`
`          },`
`        };`

### Expected
DRM content should be played smothly

### Error output
core.js:15724 ERROR TypeError: Cannot read property 'byterange' of undefined
    at generateSidxKey (videojs-http-streaming.es.js:10857)
    at videojs-http-streaming.es.js:11488
    at Object.callback (videojs-http-streaming.es.js:1420)
    at cbOnce (index.js:62)
    at XMLHttpRequest.loadFunc [as __zone_symbol__ON_PROPERTYload] (index.js:129)
    at XMLHttpRequest.wrapFn (zone.js:1332)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)

### reproduce
Inorder to reproduce this issue u need to play a DRM content

### videojs-http-streaming version
videojs-http-streaming 1.10.2

### videojs version
    "video.js": "^6.8.0",
### Other videojs lib version used
    "videojs-contrib-quality-levels": "^2.0.9",
    "videojs-flash": "^2.2.0",
    "videojs-contrib-eme": "^3.5.0",
    "videojs-contrib-dash": "^2.11.0"
### Browsers
chrome

### Platforms
os: Ububdu 18

**Comment by squarebracket** [comment] 2019-06-11 13:22
Duplicate of #457

**Closed by squarebracket** 2019-06-11 13:22 UTC
Labels: duplicate
