### ISSUE TITLE
Catching And Handling e.segments[s] is undefined

### ISSUE THREAD

**Issue by ProdigyView** [videojs/http-streaming#985] opened 2020-11-02 22:25 UTC
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

Before opening an issue see if your problem can be resolved with the [troubleshooting guide](https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md). 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin you can use.
I have multiple m3u8 files that are played one after another. I use the same url on Node-Media-Server for a livestream. Occasionally I get this error: e.segments[s] is undefined

```
VIDEOJS: ERROR: TypeError: e.segments[s] is undefined
    G videojs-http-streaming.min.js:2
    getExpiredTime videojs-http-streaming.min.js:3
    stuckAtPlaylistEnd_ videojs-http-streaming.min.js:7
    setupMasterPlaylistLoaderListeners_ videojs-http-streaming.min.js:7
    dispatcher video.min.js:12
    pe video.min.js:12
    trigger video.min.js:12
    haveMetadata videojs-http-streaming.min.js:2
    request videojs-http-streaming.min.js:2
    te videojs-http-streaming.min.js:2
    s videojs-http-streaming.min.js:2
    s video.min.js:19
    e video.min.js:19
    ii video.min.js:19
    ti video.min.js:19
    e videojs-http-streaming.min.js:2
    t videojs-http-streaming.min.js:2
    dispatcher video.min.js:12
    pe video.min.js:12
    trigger video.min.js:12
    mediaUpdateTimeout videojs-http-streaming.min.js:2
    setTimeout handler*R</n.haveMetadata videojs-http-streaming.min.js:2
    request videojs-http-streaming.min.js:2
    te videojs-http-streaming.min.js:2
    s videojs-http-streaming.min.js:2
    s video.min.js:19
    e video.min.js:19
    $$initLivestreamPlayer$$$/$check404Interval$$< main.js:2231
    setInterval handler*$$initLivestreamPlayer$$$ main.js:2230
    $$$scope$$$init$/< main.js:2222
    jQuery 9
    $$$scope$$$init$ main.js:2222
    Angular 21
    jQuery 13
```
## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

Hard to reproduce, doesn't always happen. But it involves changing m3u8 videos that use the same stream.

### Expected
Please describe what you expected to happen that did not happen in the description.

## Additional Information
Please include any additional information necessary here. Including the following:
Is there a way of catching this in a try catch or an on error?

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.2.3

### videojs version
what version of videojs does this occur with?
video.js 7.8.4

### Browsers
what browsers are affected? please include browser and version for each
*Mostly firefox

### Platforms
what platforms are affected? please include operating system and version or device and version for each
*Desktop

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* videojs playlist

**Comment by gkatsev** [comment] 2020-11-17 22:38
Can you elaborate on what you mean by "But it involves changing m3u8 videos that use the same stream."?
Have a stream you can provide? Or better yet a reduced example where it happens (the more reliably the better, but understand that sometimes it is intermittent).

**Comment by atyachin** [comment] 2020-12-23 23:41
An easy way to reproduce the issue:
1. setup nginx + RTMP Module to create HLS fragments for a live RTMP endpoint (see: https://github.com/arut/nginx-rtmp-module)
2. Start streaming from OBS to the RTMP endpoint
3. Start videojs to play the m3u8 file
4. stop streaming in OBS --> m3u8 us deleted --> 404 --> videojs tries to reload the m3u8
5. start streaming again in OBS --> new m3u8 is generated (segments sequence restarts) --> loaded by videojs --> 'duration' error

check this comment:
https://github.com/surmon-china/vue-video-player/issues/302#issuecomment-643761370

**Comment by gkatsev** [comment] 2021-01-05 22:05
If I'm reading the linked issue correctly, the manifest is updated without a discontinuity and the segments that were previously in the manifest have been removed and new segments included?

**Comment by gkatsev** [comment] 2021-01-05 23:21
Does the media sequence jump to account for the removed segments?

**Comment by gkatsev** [comment] 2021-01-06 17:09
Also, the behavior you described is invalid HLS. If nginx-rtmp-module is doing this, it would be good to open an issue with them to have them add a discontinuity tag when this happens.

**Comment by atyachin** [comment] 2021-01-30 14:58
@gkatsev Some correction for the manifest behavior:
On short disconnect (say OBS stop/start), the manifest does get the discontinuity flag and the sequence continues. In this case videojs resumes playback properly.

on longer disconnect (or nginx restart), the manifest is restarted, meaning no discontinuity flag but the #EXT-X-MEDIA-SEQUENCE starts from zero again. In this case videojs does try to reload the manifest (it gets 404 until the new manifest is ready),  and once reloaded it starts throwing the "TypeError: Cannot read property 'duration' of undefined" error.

**Comment by royvs33** [comment] 2021-02-04 15:15
@gkatsev @atyachin I can confirm that I am experiencing the same behavoir, we want to make sure that the video restarts on the client every time our connection would drop or change. I cannot create an exact test case as this involves restarting the nginx server. But I can show the contents.
Let's say a stream is running fine, this would be this result in the m3u8 file:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:2479
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
1612451202500.ts
#EXTINF:2.000,
1612451204500.ts
#EXTINF:2.000,
1612451206500.ts
#EXTINF:2.000,
1612451208500.ts
#EXTINF:2.000,
1612451210500.ts
```

I would then stop nginx. And then there are both `video.js:84 VIDEOJS: WARN: Problem encountered with playlist 0-index.m3u8. Trying again since it is the only playlist.` and `GET index.m3u8 net::ERR_CONNECTION_REFUSED` log messages. This is fine as it keeps retrying.
When I would then restart the server the following response is given:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY
#EXTINF:2.000,
1612451385500.ts
```
This is then being extended to 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY
#EXTINF:2.000,
1612451385500.ts
#EXTINF:2.000,
1612451387500.ts
#EXTINF:2.000,
1612451389500.ts
#EXTINF:2.001,
1612451391500.ts
#EXTINF:2.460,
1612451393500.ts
```
And eventually the `#EXT-X-DISCONTINUITY` is being removed:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
1612451387500.ts
#EXTINF:2.000,
1612451389500.ts
#EXTINF:2.001,
1612451391500.ts
#EXTINF:2.460,
1612451393500.ts
#EXTINF:2.000,
1612451396000.ts
```

The problem is that after the first response from the server after the restart loading the manifest file gives the error as described, although the `#EXT-X-DISCONTINUITY` is present
```
VIDEOJS: ERROR: TypeError: Cannot read property 'duration' of undefined
    at sumDurations (video.js:39330)
    at SyncController.getExpiredTime (video.js:54974)
    at MasterPlaylistController.onSyncInfoUpdate_ (video.js:57950)
    at SegmentLoader.<anonymous> (video.js:57285)
    at SegmentLoader.data.dispatcher (video.js:1915)
    at trigger (video.js:2051)
    at SegmentLoader.EventTarget.trigger (video.js:2454)
    at SegmentLoader.playlist (video.js:51483)
    at MasterPlaylistController.handleUpdatedMediaPlaylist (video.js:57148)
    at PlaylistLoader.<anonymous> (video.js:57052)
```

**Comment by gkatsev** [comment] 2021-02-10 23:01
@royvs33 thanks, that's incredibly useful. Unfortunately, it's showing an invalid stream, which makes it near impossible to recover from. First, the MEDIA-SEQUENCE gets reset to 0, but then we don't get a DISCONTINUITY-SEQUENCE number with the newly added discontinuity, especially once the disco tag is removed from the playlist.
This isn't really something we can handle in the player, unfortunately.

**Comment by royvs33** [comment] 2021-02-16 06:45
> @royvs33 thanks, that's incredibly useful. Unfortunately, it's showing an invalid stream, which makes it near impossible to recover from. First, the MEDIA-SEQUENCE gets reset to 0, but then we don't get a DISCONTINUITY-SEQUENCE number with the newly added discontinuity, especially once the disco tag is removed from the playlist.
> This isn't really something we can handle in the player, unfortunately.

Thank you @gkatsev , that makes it clear for me. I'll check if we can get it fixed in the server.

**Closed** 2022-04-19 17:15 UTC
Labels: outdated
