### ISSUE TITLE
Infinite Load on (some?) MPEG-DASH inputs

### ISSUE THREAD

**Issue by rhyswilliamsza** [videojs/http-streaming#865] opened 2020-06-14 14:41 UTC
## Description

For certain mpeg-dash mpd inputs (both live + vod), VideoJS fails to start the video, ultimately leaving the viewer with an indefinite loading indicator (rotating loader). The timeline, duration & liveui load fine; the video buffers (as confirmed through chromes network inspection as well as via the loading indicator on the timeline), however the video just doesn't start?

There are no log outputs to indicate any failures. Everything looks normal.

The odd part: this only happens on certain sources. Most of our sources have very similar encodings, and I haven't been able to track down a specific encoding parameter which induces it. It seems to be kind of random, however stays consistent on _which_ files **randomly** don't work (I know, I don't make sense). Anywho, not sure what differences cause the issue.

I have stepped through versions of the `http-streaming` plugin, and have found the bug/breaking change is introduced in the fix for #666 (1.11.1). 1.11.0 works perfectly, however everything after that faces the same issue.

## Demonstration
https://jsbin.com/dikatamuwu/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play File
2. Infinite Load
3. Change to 1.11.0. Repeat.

### Expected
Video to start playing.

### Error output
None

### videojs-http-streaming version
videojs-http-streaming >= 1.11.1

### videojs version
Irrelevant

### Browsers
All Chrome
All Safari
All Mobile Chrome

### Platforms
All Tested

### Other Plugins
None

### Other JavaScript
None

**Comment by gkatsev** [comment] 2020-06-14 15:31
Your sample seems to be playing fine here https://videojs-http-streaming.netlify.app/, which uses an RC version of our playback engine. We hope to get that version released in a week or two.

**Comment by gkatsev** [comment] 2020-06-14 15:40
Oops, didn't realize this was on the VHS repo.
The above link loads what's in master currently.

It is interesting that it seems that #666 causes the issue, but our dash handling in the upcoming version is much improved.

**Comment by rhyswilliamsza** [comment] 2020-06-14 17:02
Cool! No stress, thanks for the info. I'll keep an eye out for the new playback engine upgrades. Hopefully master has fixed the issue :)

**Comment by gkatsev** [comment] 2020-06-30 05:24
The es.js file is for usage with bundlers like webpack and not directly.

**Comment by rhyswilliamsza** [comment] 2020-07-01 16:47
Yip. However this happens when building with webpack. If I use the core .js file in my webpack bundle as a module, all works well. However, if I use the es module, I face the same issue :/

**Comment by shirtjs** [comment] 2020-07-26 18:16
I can reproduce this issue on Videojs 7.8.4.

**Comment by rhyswilliamsza** [comment] 2020-09-09 09:47
I am experiencing this again on the latest 2.1.0 release. Not sure why it's popped up again

**Closed** 2020-12-25 11:47 UTC
Labels: outdated
