### ISSUE TITLE
Anamorphic Video is sized differently between the Browsers

### ISSUE THREAD

**Issue by abstrakt1** [videojs/http-streaming#551] opened 2019-06-14 12:46 UTC
## Description
I have an anamorphic HLS-Video with a resolution of 720:576 and a sample-aspect-ratio of "64:45".

(I have the same video as a DASH-Stream and there it is also streched in chrome, happens only in combination with HLS)

In Firefox it is scaled to a width of 1024. (65:45 or 1.42..) -> 720* 1.42.. = 1024

<a href="https://ibb.co/F32DBCy"><img src="https://i.ibb.co/F32DBCy/firefox.jpg" alt="firefox" border="0"></a>

In Chrome its not scaled.

<a href="https://ibb.co/GV0Pykh"><img src="https://i.ibb.co/GV0Pykh/chrome.jpg" alt="chrome" border="0"></a>

### Expected
Expected behaviour is, that the player scales up the video to 1024.

## Additional Information
hls
anamorphic video
sample-aspect-ratio "64:45"
resolution 720x576

from segment ts-file
```nals
access_unit_delimiter_rbsp
seq_parameter_set_rbsp
chroma_format_idc	1
video_format	5
color_primaries	2
transfer_characteristics	1
sample_ratio	1.4222222222222223
```

### videojs version
video.js 7.5.4

### Browsers
what browsers are affected? please include browser and version for each
actual chrome version
actual firefox version

**Comment by sebst3r** [comment] 2019-06-18 09:28
Thanks for reporting! I have the exact same issue :S

**Comment by elpiojo86** [comment] 2019-06-18 09:37
Encountered the same issue. Would be great to have a fix for this.

**Comment by SebKei** [comment] 2019-08-20 09:20
Issue still present with videojs 7.60 and Chrome 76.
When will this be fixed?

**Comment by emkman99** [comment] 2019-08-20 12:35
This can be closed, as it's a duplicate of https://github.com/videojs/http-streaming/issues/312.

**Closed** 2019-10-26 13:34 UTC
Labels: outdated
