### ISSUE TITLE
Video error on loop of HLS content

### ISSUE THREAD

**Issue by jgcaruso** [videojs/http-streaming#1401] opened 2023-05-23 20:26 UTC
## Description
When there is a looping video (one or more on the same page) the players all fail to restart and display an error on screen

[Multiple videos](https://cloudy-nervous-molecule.glitch.me/index.html) - error on loop
[Single video](https://cloudy-nervous-molecule.glitch.me/index-single.html) - error on loop
[Multiple videos, no looping](https://cloudy-nervous-molecule.glitch.me/index-noloop.html) - no error

[Fragmented mp4, multiple videos](https://cloudy-nervous-molecule.glitch.me/fmp4-test.html)

<img width="1736" alt="SCR-20230523-jisl" src="https://github.com/videojs/http-streaming/assets/4081020/cdf40929-4d06-488d-9cc7-b3f1a1087a1a">

## Sources
I've had this issue with my own source media (fragmented mp4 files) as well as the demo source media from videojs ["advanced examples" page](https://videojs.com/advanced/?video=disneys-oceans)

**videojs example sources - used in first 3 test pages above**
https://d2zihajmogu5jn.cloudfront.net/elephantsdream/hls/ed_hd.m3u8
https://d2zihajmogu5jn.cloudfront.net/sintel/master.m3u8
https://d2zihajmogu5jn.cloudfront.net/big-buck-bunny/master.m3u8

**Some of my own source media - used in fragmented test page above**
https://videos.files.wordpress.com/EnQKgGDc/video-a52836b5c2_mp4.adaptive_4.m3u8
https://videos.files.wordpress.com/g6bCyLO7/molly_iphone_img_4058_mov.adaptive_4.m3u8
https://videos.files.wordpress.com/NGYE1Hqy/video-206c645332_mp4.adaptive_3.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open the provided reproduction pages from the description in Firefox
2. if the videos aren't set to auto play, press play
3. skip to the end of each of the videos (last 10 seconds)
4. wait for the videos to end, they will all show an error message instead of looping
5. for the page with looping disabled, the videos should play to the end

### Expected
The videos should loop without failing

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:

<img width="2306" alt="SCR-20230523-jjcf" src="https://github.com/videojs/http-streaming/assets/4081020/76b3aa2f-16c3-40da-9853-32650a8228cb">

```
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a473c864-727a-436c-bc43-05704e9e1636 could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Object { code: 3, message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." }
[video.js:206:47](https://vjs.zencdn.net/8.3.0/video.js)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a473c864-727a-436c-bc43-05704e9e1636 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009) [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a31c6d07-467d-4586-89c1-f98cb004c78f could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Object { code: 3, message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." }
[video.js:206:47](https://vjs.zencdn.net/8.3.0/video.js)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a31c6d07-467d-4586-89c1-f98cb004c78f could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009) [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/c3db30fc-a390-40a3-8bb7-910ba9a94663 could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Object { code: 3, message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." }
[video.js:206:47](https://vjs.zencdn.net/8.3.0/video.js)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/c3db30fc-a390-40a3-8bb7-910ba9a94663 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009) [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a31c6d07-467d-4586-89c1-f98cb004c78f could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a473c864-727a-436c-bc43-05704e9e1636 could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/c3db30fc-a390-40a3-8bb7-910ba9a94663 could not be decoded. [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
Media resource blob:https://cloudy-nervous-molecule.glitch.me/a31c6d07-467d-4586-89c1-f98cb004c78f could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_WAITING_FOR_DATA (0x806e0009) [index.html](https://cloudy-nervous-molecule.glitch.me/index.html)
```

## Additional Information

This seems to be easily reproduced in Firefox. I think I've seen similar issues in Chrome, but at the moment I'm not able to reproduce there. Its possible what I recall seeing in Chrome is a different issue that just presents the same error screen.

### videojs-http-streaming version

videojs-http-streaming 2.16.2 and 3.3.1

- using the distributed versions from https://unpkg.com/browse/@videojs/http-streaming@2.16.2/dist/videojs-http-streaming.js and https://unpkg.com/browse/@videojs/http-streaming@3.3.1/dist/videojs-http-streaming.js

### videojs version
video.js 8.3.0

### Browsers
what browsers are affected? please include browser and version for each
* firefox 113.0.2

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* macos (don't have a windows machine to try with)

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* nope

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* nope

**Comment by adrums86** [comment] 2023-05-23 22:33
Hi @jgcaruso, I suspect the issue is actually fixed in FireFox 115. I ran into this bug a while ago and discovered it was an issue with setting the `loop` attribute on the video element combined with source buffer trimming, so I filed a bug. 
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1829086.

You can test against https://www.mozilla.org/en-US/firefox/115.0a1/releasenotes/

If that doesn't work please tag me and I'll gladly take a closer look.

**Comment by jgcaruso** [comment] 2023-05-24 14:34
@adrums86 thanks for that!

It does seem to be working well in Firefox 115! I've had the videos playing for a while now, refreshing occasionally as well.

**Comment by adrums86** [comment] 2023-05-26 21:08
Closing this since it seems to be a FireFox issue. Feel free to open a new issue if necessary.

**Closed by adrums86** 2023-05-26 21:08 UTC
