### ISSUE TITLE
Freezing videos when using HLS from cloudflare on chrome

### ISSUE THREAD

**Issue by odoumas** [videojs/http-streaming#1404] opened 2023-05-31 07:17 UTC
## Description
Per title. Some cloudflare videos appear to freeze, but only in chrome. On firefox there is a visible "gap", but it handles it gracefully.

[Example](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fcustomer-e5dv0zdx7q80qq2x.cloudflarestream.com%2Fe0f7c6a0f53e4274b1afb05e7b96e45d%2Fmanifest%2Fvideo.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false)

The [same](https://hlsjs.video-dev.org/demo/?src=https%3A%2F%2Fcustomer-e5dv0zdx7q80qq2x.cloudflarestream.com%2Fe0f7c6a0f53e4274b1afb05e7b96e45d%2Fmanifest%2Fvideo.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==) but on hls.js

Both should be opened on Chrome to reproduce the issue

## Sources
This appears on multiple sources, see above for an example

## Steps to reproduce
Just visit the links

### Expected
The video plays uninterupted

### Error output
No error output

## Additional Information
While inverstigating, I had managed to reproduce the issue also on hls.js. However, it appears that they fixed this fairly recently. Relevant [PR](https://github.com/video-dev/hls.js/pull/5500). Maybe it can be of help.

### videojs version
latest, reproduced accross multiple versions on both 7 and 8 

### Browsers
Version 112.0.5615.165 (Official Build) (64-bit)

### Platforms
Debian bullseyeing any other javascript libraries or frameworks on the page? if so please list them below.

**Comment by adrums86** [comment] 2023-06-06 03:35
Thanks for filing an issue and providing an example. I can easily reproduce this in the demo page with the media you provided. The PR in hls.js is very helpful as a reference, if that is indeed the same problem it might actually be in [mux.js](https://github.com/videojs/mux.js). Labeling this for further investigation.

**Comment by hitech95** [comment] 2023-06-15 18:52
We are facing this issue too, this and the quality that switch continuously.
(Cloudlare stream)

I think that the video quality is due to small fragments and the connection time is highter than the transmission time so the bandwith caculation is wrong lowering the quality.

**Comment by philefstat** [comment] 2023-06-16 11:46
Facing the same issue and if helpful, we're not using mux, just video.js and cloudflare directly

**Comment by adrums86** [comment] 2023-06-23 17:18
I appreciate the additional information. I'll spend some time digging into this today and update this issue with my findings.

**Comment by adrums86** [comment] 2023-06-26 06:57
I wasn't able to spend as much time on this as I'd have liked on Friday, but I did some more poking around in mux over the weekend. I suspect the solution does lie in there. I'm not aware of any configuration of http-streaming that uses anything other than mux.js for transmuxing, please correct me if I'm wrong though. I think we might need to adjust some of the `getGopForFusion_` calculation in the `mp4/transmuxer`. I'm consistently seeing a small (~.1 second) buffer gap in the [sample media provided](https://customer-e5dv0zdx7q80qq2x.cloudflarestream.com/e0f7c6a0f53e4274b1afb05e7b96e45d/manifest/video.m3u8) at the end of the first segment, which is causing the freezing/jumping behavior. 
<img width="246" alt="bufferGap" src="https://github.com/videojs/http-streaming/assets/10353591/ea042e94-6724-4f5a-ab88-472edea42d18">
I did some playing around with [this line](https://github.com/videojs/mux.js/blob/dc56f1b79224bf20dc34ec1e949df6b18c2ffde4/lib/mp4/transmuxer.js#L547) but ran out of time this weekend. I'll make some more time to do some proper debugging this week. If anyone else sees a better approach or is able to make more progress please let me know.

**Comment by hitech95** [comment] 2023-06-26 07:09
@adrums86 If you need an example of our videojs implementation or access to more video sources please let me know!

**Comment by adrums86** [comment] 2023-07-20 19:30
Been quite busy over the past few weeks, I'm working on prioritizing this issue internally. Will update this thread accordingly.

**Comment by adrums86** [comment] 2023-11-13 21:46
I was looking back trying to re-address some older issues. After testing this media again I can't reproduce the freezing anymore. Tested side by side in Safari, Chrome, and Firefox on an M1 Mac and playback was consistent without freezing or skipping. Going to close this issue for now, we can re-open if anyone is still able to reproduce this.

**Closed by adrums86** 2023-11-13 21:46 UTC
Labels: needs: research

**Comment by hitech95** [comment] 2023-11-13 22:21
@adrums86 What VideoJS version did you tested with?
We are still facing the issues so in case I can provde access to our implementation. 

We are using VideoJS from NPM:
```json
"dependencies": {
  ...
  "video.js": "^7.20.0",
  ...
}
```
If you tested with an updated version is there a way to overrinde the `http-streaming` component with an older core VideoJS version?

**Comment by odoumas** [comment] 2023-11-14 06:54
Cloudflair pushed a fix/improvement recently, so my examples won't exhibit the faulty behaviour anymore.

**Comment by hitech95** [comment] 2023-11-29 14:37
> @hitech95 I was testing in the [v3.7.0 VHS demo page](https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fcustomer-e5dv0zdx7q80qq2x.cloudflarestream.com%2Fe0f7c6a0f53e4274b1afb05e7b96e45d%2Fmanifest%2Fvideo.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&offset-each-segment=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false) with the asset originally provided by @odoumas https://customer-e5dv0zdx7q80qq2x.cloudflarestream.com/e0f7c6a0f53e4274b1afb05e7b96e45d/manifest/video.m3u8, but it seems like cloudflare made some changes as well. Does anyone have any other assets that have the same issue that I could debug with? Thanks in advance!

Please can you try with our asset:
https://customer-1bvq8nsj2ktnfpil.cloudflarestream.com/49e66b45541d0998894a478b75d81c8c/manifest/video.m3u8

We are still facing blurring and segments get skipped.
while with the cloudflare player it is not:
https://customer-1bvq8nsj2ktnfpil.cloudflarestream.com/49e66b45541d0998894a478b75d81c8c/watch
