### ISSUE TITLE
Feature: Alternate renditons for video tracks

### ISSUE THREAD

**Issue by Llorito** [videojs/http-streaming#116] opened 2018-06-26 15:27 UTC
Description
Adds support for alternate renditions video tracks. Analogous implementation to alternate audio renditions and text tracks.

The same was proposed in videojs-contrib-hls
https://github.com/videojs/videojs-contrib-hls/pull/1128

**Comment by Llorito** [comment] 2018-11-29 10:56
Hey everyone... Do you know whether there's a plan to have this in a release soon?

Thanks

**Comment by gesinger** [comment] 2020-05-08 14:58
Closing as a duplicate of https://github.com/videojs/http-streaming/issues/363

**Closed by gesinger** 2020-05-08 14:58 UTC
Labels: enhancement, planned
