### ISSUE TITLE
VOD Dash stream not working

### ISSUE THREAD

**Issue by papigers** [videojs/http-streaming#209] opened 2018-08-25 23:16 UTC
## Description
Hi, for some reason videos I encode using ffmpeg and MP4Box are not being able to stream on your demo. They do however stream, on shaka player's demo, and on `videojs-contrib-dash`.

## Sources
I've made a specific video I've uploaded to S3 public, so you can check my issue: the URL:
https://s3.eu-central-1.amazonaws.com/bucketvod/b0PCWLt690M9/mpd.mpd
I've removed CORS.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go to [your demo](https://videojs.github.io/http-streaming/) and insert the URL I gave and select the matching type (dash+xml), You should see that loading the video does nothing. 
2. Go to [shaka player demo](https://shaka-player-demo.appspot.com/demo/#asset=https://s3.eu-central-1.amazonaws.com/bucketvod/b0PCWLt690M9/mpd.mpd;lang=en-US;build=uncompiled) and you should see that the player loads the video properly.
3. Go to [videojs-contrib-dash demo](https://videojs.github.io/videojs-contrib-dash/), enter the URL and again, the video loads properly.

## Results
Video is loading on all demos but http-streaming demo.
I've also tried loading on my own app using videojs and ur lib, but again no luck.

### Expected
Video should load properly as it does on other players.

### Error output
No errors are shown as u can see.

## Additional Information
I'm currently using `videojs-contrib-dash`, but in my understanding http-streaming is now the official http streaming plugin for both hls and dash, so I want to migrate.
At first I thought it was some king with my encoding process, but then I saw that other players have no problems with it.

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with? the current version accessible by the demo/npm.

### Browsers
what browsers are affected? please include browser and version for each
* Tetsted only on my chrome 

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Win10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* No plugins.

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* Your demo.

**Comment by forbesjo** [comment] 2018-08-27 15:44
Looks like a similar issue https://github.com/videojs/video.js/issues/5289

**Comment by papigers** [comment] 2018-08-27 16:32
Seems to be the case, but no helpful information there.

**Comment by papigers** [comment] 2018-08-31 17:18
Bump?

**Comment by Fruitsapje** [comment] 2018-10-02 09:03
Hi there,

I was wondering if there is any update on this issue. We are experiencing the same problems as described by the OP. Do you think you are able to solve this problem in the near future or would your advice be to include the `videojs-contrib-dash` project instead?

Thanks in advance!

**Comment by edwinbradford** [comment] 2018-11-05 14:55
Same problem here. My streams worked with videojs-contrib-dash and work in the Shaka Player and the DASH Reference Client but I'm having multiple issues with video.js 7.x.. I tried changing the encoding profile from live to on-demand with two different encoding pipelines using different tools and both fail to play in video.js 7.x. The live profile plays but always selects the lowest bandwidth available and stutters at the end of the video.

I'm going to use video.js core from the dist/alt directory that doesn't bundle http-streaming and include dash and hls support separately as before.

**Comment by Dardaxe** [comment] 2018-12-11 15:31
Hi, 
I'm having the same problems with google chrome only. 

I've check manifest given in this issue [videojs/video.js#5669](https://github.com/videojs/video.js/issues/5669) from yesterday about dash problems on safari.
This manifest is working correctly on [http-streaming demo page](https://videojs.github.io/http-streaming/) AND [videojs-contrib-dash demo page](https://videojs.github.io/videojs-contrib-dash/)

I'm trying to understand why his manifest is working correctly on both plugins and mine is not.
I'm wondering if it could be a transcoding issue.

Can you tell me which service/tool you've used to transcode your videos @papigers ?

Thanks in advance

**Comment by papigers** [comment] 2018-12-11 16:33
@Dardaxe I'm still having issues with http-streaming as the issue suggests. That's why I'm using contrib-dash for now.
I've used ffmpeg with libx264

**Comment by papigers** [comment] 2018-12-26 14:16
@forbesjo Any solution?

**Comment by majamee** [comment] 2019-01-09 14:48
I guess, I've got the same problem:
issue, source code and demo can be found here:
https://alpine-dash-hls.gq/demos/videojs/videojs-vhs-v7

Please let me know what to do to fix the situation.

**Comment by Dardaxe** [comment] 2019-01-21 16:53
Hi, 
Got some news about this issue.

It looks like videoJS player requires frame rate of video and sample rate of audio streams to align to playback in Chrome. Here is an example of frame rate, GOP Size, Segment size, and audio config that works with Dash on Chrome/Firefox: 
![image 2](https://user-images.githubusercontent.com/9088465/51488205-36572180-1da5-11e9-9aad-69a9a3eba89d.png)

Hope it can help you

**Comment by majamee** [comment] 2019-02-01 09:58
Thank you for the hint, but what I am really looking for is that VHS for videojs gets finally a documentation how to use it with MPEG-Dash, best including an example like it was provided for videojs v6:
https://videojs.github.io/videojs-contrib-dash/

Btw. the exact same video source works in videojs v6, sample provided here: https://alpine-dash-hls.gq/demos/videojs
So I guess VHS has to still finish the work on DASH, any news about that? Reading the blog, reading on Github, searching the net, but no information so far... Any additional input on this would be appreciated.

**Comment by edwinbradford** [comment] 2019-02-01 11:06
I have to agree with @majamee. The hint is really interesting but I no longer have the time to research into it further.

Would it be possible to provide documentation on which command line tools and settings are expected to work so that we can try and reproduce a single working example to test against?

Personally I'm using FFmpeg as it can now handle every stage from initial encoding to the final packaging.

**Comment by majamee** [comment] 2019-02-01 13:58
@edwinbradford so far all I could do is to create a workaround for version 7.x with working HLS & DASH, which can be found here: 
https://alpine-dash-hls.gq/demos/videojs

It uses video.core.js (video.js without VHS) and includes instead:
* https://cdn.dashjs.org/latest/dash.all.min.js
* https://cdn.jsdelivr.net/npm/videojs-contrib-dash/dist/videojs-dash.min.js

Doing so the exact same video sources are working fine. Maybe this is helpful to you as well.

**Comment by edwinbradford** [comment] 2019-02-27 09:30
Thanks, I did the same as you and also included [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) for HLS streams. However I haven't been able to create any streams that are reliable enough to depend on for production purposes so I've put everything on hold and fallen back to mp4s until DASH and HLS pipeline tools become a little more mature.

**Comment by majamee** [comment] 2019-02-27 13:22
@edwinbradford Did you maybe have a look at the pipeline I created at https://alpine-dash-hls.gq as it seems pretty much stable and production ready. ;)

**Comment by edwinbradford** [comment] 2019-02-27 14:03
No I missed it... I wish I'd seen your pipeline before I spent months trying to develop my own as it's outside my skill set. I'm working on other projects now but it looks like you're using FFmpeg, MP4Box and something else.

In case you're interested I finished with [this script](https://github.com/edwinbradford/fffmp4/blob/master/ffmp4.bat). I wrote it for my own use and I'm not a developer, it's Windows only but you can view the core FFmpeg commands and it doesn't require any other tools.

It seems to produce valid streams.

**Comment by majamee** [comment] 2019-02-27 14:22
As long as you are able to use Docker (https://docs.docker.com/docker-for-windows/install/) you can use the pipeline following the instructions provided as it is. Haven't tested it on Windows myself though, so feedback is welcome.

**Comment by gkatsev** [comment] 2019-04-08 18:05
So, based on the mdp example on apline-dash-hls.gq, this looks like a SIDX stream? Though, I couldn't test it, we have SIDX support coming soon, see #455.

**Comment by majamee** [comment] 2019-04-08 19:43
> So, based on the mdp example on apline-dash-hls.gq, this looks like a SIDX stream? Though, I couldn't test it, we have SIDX support coming soon, see #455.

Yes, this sounds very promising. The playlist.mpd is created by using: https://gpac.wp.imt.fr/mp4box/dash/

Maybe this helps and provides you some background information. :)

**Comment by gkatsev** [comment] 2019-04-08 19:52
@majamee would you be able to fix your test stream for us to try it out?

**Comment by majamee** [comment] 2019-04-09 08:57
@gkatsev I am happy to assist, but I need a little bit more details, what you mean with could you fix it? I can provide you the direct link to the playlist file already to make it easier to specify what you are looking for:
http://alpine-dash-hls.gq/player/playlist.mpd

**Comment by gkatsev** [comment] 2019-04-09 17:27
@majamee when I try to use that mpd, I get HTTP 520 when downloading the files. The mpd loads but not anything else.

**Comment by majamee** [comment] 2019-04-09 18:56
@gkatsev I think my web hoster doesn't allow the playback from other sites (cross). Therefore I created a package with everything required including videojs and .htaccess (if you are using Apache) for you, which you can find here:
https://mega.nz/#F!rYhVCISQ!kvVDdbnTx2xls-0i4Lu2VQ

I hope this is helpful. :) Please let me know if you are requiring anything else.

**Comment by gkatsev** [comment] 2019-04-09 19:35
Awesome, thanks. I'll let you know if I need anything else.

**Comment by gkatsev** [comment] 2019-04-09 19:40
I can confirm that this source works locally with the SIDX PR (#455)

**Comment by majamee** [comment] 2019-04-09 20:12
That's great news, looking forward to test it upon release :)

**Comment by gkatsev** [comment] 2019-04-12 14:41
#455 has been merged, we'll be releasing soon.

**Closed by gkatsev** 2019-04-12 14:41 UTC
Labels: bug, planned

**Comment by majamee** [comment] 2019-06-02 03:09
> #455 has been merged, we'll be releasing soon.

May I ask, if there is any ETA about merging the version of http-streaming into vidojs, I've seen last merged version according to release notes seems to be a version previous to this improvement? Thank you very much.

**Comment by nimishsinghal** [comment] 2020-07-31 20:59
Hi,

I saw the PR merged but I am still facing this issue in the latest version of 7.8.1 version of Videojs, please refer to sample demo https://jsbin.com/solukovuja/1/edit?html,output. The video is working fine in https://videojs.github.io/videojs-contrib-dash/.

It is getting stuck in this state.
<img width="1440" alt="Screenshot 2020-08-01 at 2 28 55 AM" src="https://user-images.githubusercontent.com/4672630/89076900-cf092d00-d39e-11ea-8c6f-77aa15ca2ed8.png">
